### PR TITLE
added image

### PR DESCRIPTION
**Pull request by webbdm**
@sward42

Still need to add Bootstrap and the xhr request part, but it's functional as is.

You should definitely take a look.

### CODE REVIEW

**Comment by sward42** [comment]
Love the background image...exactly what I think of for a department store!
I know you are still working on it, but one thing I noticed was that all of the prices are changing, not just the dept associated with the season discount.  May want to take a look at how to isolate the specific department.

**Comment by webbdm** [comment]
I totally overlooked that instruction guideline :(

**Comment by sward42** [comment]
Winter and Autumn are changing the correct depts.  Spring has a bug in line 87 of your seasons.js file; you used the wrong letter for the counter.  Changing that will get Spring working properly.  Can't figure out why toFixed isn't working on all of the items.

**Comment by webbdm** [comment]
Fixed :octocat:

**Comment by sward42** [comment]
👍   Looks good!

**Pull request merged**
